[package]
name = "nlj-ic-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk.workspace = true
ic-wasi-polyfill.workspace = true
nlj-core.workspace = true
csyncify.workspace = true